name: Push
on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Run tests
        run: uv run pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
  code-quality:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: astral-sh/setup-uv@v5
      - name: Install dependencies
        run: uv sync --all-extras --dev
      - name: Run black
        run: uv run black src --check
      - name: Run isort
        run: uv run isort src --check-only --profile black
      - name: Run flake8
        run: uv run flake8 src
      - name: Run bandit
        run: uv run bandit .
      - name: Run saftey
        run: uv run safety check
  docs:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: Run image
        uses: astral-sh/setup-uv@v5
      - name: install
        run: uv sync --all-extras --dev
      - name: Install Pandoc
        run: sudo apt-get install -y pandoc
      - name: Build docs
        run: |
          mkdir gh-pages
          touch gh-pages/.nojekyll
          cd docs/
          uv run sphinx-build -b html . _build
          cp -r _build/* ../gh-pages/
      - name: Deploy documentation
        if: ${{ github.event_name == 'push' }}
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: gh-pages
